---
- name: Setup AWS EC2 for dcos master...
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    instance_role: dcos-master
  pre_tasks:
    - include_vars: ../vars/common.yml
  tasks:
    - name: Starting dcos master machine
      ec2:
          instance_type: '{{ instance_type }}'
          region: '{{ aws_region }}'
          zone: '{{aws_region}}{{instance_zone}}'
          image: '{{ centos_ami }}'
          key_name: '{{ aws_key_name }}'
          vpc_subnet_id: '{{ aws_vpc_subnet_id }}'
          group_id: '{{ instance_sg_id_dcos_master }}'
          instance_profile_name: '{{ instance_profile }}'
          instance_tags:
              Name: '{{ instance_role_master }}'
              Role: '{{ instance_role }}'
              Env: '{{ aws_env }}'
          count_tag:
              Name: '{{ instance_role_master }}'
          volumes:
          - device_name: '/dev/sda1'
            volume_size: '32'
            volume_type: 'gp2'
            delete_on_termination: true
          exact_count: 1
          wait: yes

      register: ec2_info

    - name: wait for SSH to come up
      wait_for: host="{{ item.private_dns_name }}" port=22 timeout=650 state=started
      with_items: "{{ ec2_info.tagged_instances }}"

    - ec2_remote_facts:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: running
          availability-zone: '{{ aws_region }}{{ instance_zone }}'
          "tag:Role": '{{ instance_role_master }}'
      register: nodes

- name: Setup Route53
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    instance_role: dcos-master
  pre_tasks:
    - include_vars: ../vars/common.yml

  tasks:

    - name: create individual internal DNS records
      route53:
        command: create
        private_zone: no
        overwrite: yes
        zone: "{{ private_domain }}"
        record: "{{ instance_role_master }}.{{ private_domain }}"
        type: A
        ttl: 60
        value: "{{ nodes.instances[0].private_ip_address }}"

    - name: Copy templates
      template: src=roles/common/templates/hosts.j2 dest=../inventories/{{ instance_role }}

- name: Configured instances
  hosts: dcos-master
  gather_facts: true
  become: yes
  become_user: root
  vars:
    instance_role: dcos-master
  pre_tasks:
    - include_vars: ../vars/common.yml
  roles:
    - common
